name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # TURN OFF DAPP_TEST FOR NOW
  # dapp-test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       include:
  #         - os: ubuntu-latest
  #           os_attr: linux
  #     fail-fast: false
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cachix/install-nix-action@v14
  #     - uses: cachix/cachix-action@v10
  #       with:
  #         name: dapp
  #         skipPush: true
  #         signingKey: ""
  #     - name: install
  #       run: nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_8_9
  #     - name: test
  #       run: nix-shell --pure --command "export LANG=C.UTF-8 ; dapp test"

  js-test:
    runs-on: ubuntu-latest

    env:
      MNEMONIC: test test test test test test test test test test test junk

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install and compile
        run: |
          yarn install --frozen-lockfile
          yarn compile
      - name: Perform unit test
        run: |
          yarn test:hh
          yarn test:truffle
